model:  ["GIN"]
batch_size: [512]
emb_dim: [256]
drop_out: [0]
num_layers: [23]
final_mp_layers: [3]
num_mlp_layers: [2]
pooling: ["mean"]
lr: [0.001]
epochs: [1000]
lr_scheduler: ["ReduceLROnPlateau"]
lr_schedule_patience: [20]
lr_scheduler_decay_rate: [0.5]
min_lr: [2.5e-4]
threshold: [5.e-3]