model:  ["GIN"]
batch_size: [512]
emb_dim: [256]
drop_out: [0]
num_layers: [23]
final_mp_layers: [3]
num_mlp_layers: [2]
pooling: ["mean"]
lr: [0.001]
epochs: [1000]
lr_scheduler: ["ReduceLROnPlateau"]
lr_schedule_patience: [20]
lr_scheduler_decay_rate: [0.5]
min_lr: [2.5e-4]
threshold: [5.e-3]

# Knowledge Distillation
graph_emb: [0]
import_mlp_layer: [1]
node_emb: [1]
node_emb_fac: [10]
p_edge_add: [0.05]
p_edge_drop: [0.05]
p_feat: [0.2]
pred_loss: [1]
teacher: ["CWN"]
freeze_mlp_layer: [0]
generator: ["er"]