model:  ["GIN"]
epochs: [200]
emb_dim: [64]
drop_out: [0]
num_layers: [23]
final_mp_layers: [3]
num_mlp_layers: [2]
pooling: ["mean"]
lr_schedule_patience: [5]
min_lr: [0.0000001]
tracking: [0]

# Knowledge Distillation
graph_emb: [0]
import_mlp_layer: [0]
node_emb: [1]
node_emb_fac: [10]
m_p_edge_add: [0.05]
m_p_edge_drop: [0.05]
m_p_feat: [0.05]
pred_loss: [1]
teacher: ["CWN"]
freeze_mlp_layer: [0]